#!/usr/bin/env python3
"""Build deterministic MenQ Design Foundations CSS from governed sources."""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

WORKSPACE = Path(__file__).resolve().parents[1]
SOURCE_DIR = WORKSPACE / "packages/design-foundations/source"
OUTPUT_DIR = WORKSPACE / "packages/design-foundations/generated"
TOKEN_DIR = WORKSPACE / "packages/design-tokens/generated"
TOKEN_CSS = TOKEN_DIR / "tokens.css"
TOKEN_MANIFEST = TOKEN_DIR / "manifest.json"
SOURCE_FILES = (
    SOURCE_DIR / "base.css",
    SOURCE_DIR / "layout.css",
)
TOKEN_REFERENCE = re.compile(r"var\((--menq-[a-z0-9-]+)\)")
TOKEN_DECLARATION = re.compile(r"^\s*(--menq-[a-z0-9-]+):", re.MULTILINE)


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def canonical_json(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def main() -> int:
    errors: list[str] = []

    if not TOKEN_CSS.is_file() or not TOKEN_MANIFEST.is_file():
        errors.append("token artifacts must be built before foundations")

    source_parts: list[str] = []
    for path in SOURCE_FILES:
        if not path.is_file():
            errors.append(f"missing foundation source: {path.relative_to(WORKSPACE)}")
            continue
        source_parts.append(path.read_text(encoding="utf-8").rstrip() + "\n")

    if errors:
        print("FOUNDATIONS BUILD: RED")
        for error in errors:
            print(f"- {error}")
        return 1

    token_css = TOKEN_CSS.read_text(encoding="utf-8")
    declared_tokens = set(TOKEN_DECLARATION.findall(token_css))
    foundation_css = "\n".join(source_parts)
    referenced_tokens = set(TOKEN_REFERENCE.findall(foundation_css))
    unresolved = sorted(referenced_tokens - declared_tokens)
    if unresolved:
        print("FOUNDATIONS BUILD: RED")
        for token in unresolved:
            print(f"- unresolved token reference: {token}")
        return 1

    combined_css = (
        "/* Generated by build_foundations.py. Canonical source remains repository contracts and source CSS. */\n"
        + token_css.rstrip()
        + "\n\n"
        + foundation_css
    )
    css_bytes = combined_css.encode("utf-8")

    token_manifest = json.loads(TOKEN_MANIFEST.read_text(encoding="utf-8"))
    source_records = []
    for path in SOURCE_FILES:
        data = path.read_bytes()
        source_records.append(
            {
                "path": str(path.relative_to(WORKSPACE)).replace("\\", "/"),
                "bytes": len(data),
                "sha256": sha256_bytes(data),
            }
        )

    manifest = {
        "schemaVersion": 1,
        "package": "@menq/design-foundations",
        "tokenManifestSha256": sha256_bytes(TOKEN_MANIFEST.read_bytes()),
        "tokenSourceSha256": token_manifest["sourceSha256"],
        "sources": source_records,
        "artifacts": [
            {
                "path": "foundations.css",
                "bytes": len(css_bytes),
                "sha256": sha256_bytes(css_bytes),
            }
        ],
        "generatedOutputsAreCanonical": False,
    }

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUTPUT_DIR / "foundations.css").write_bytes(css_bytes)
    (OUTPUT_DIR / "manifest.json").write_text(canonical_json(manifest), encoding="utf-8")

    print("FOUNDATIONS BUILD: GREEN")
    print(
        f"Built foundations.css from {len(SOURCE_FILES)} governed sources with "
        f"{len(referenced_tokens)} token references."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
